[package]
name = "authorsphere"
version = "0.1.0"
edition = "2024"

[dependencies]
beryllium = "0.13.3"
json = "0.12.4"
pixel_formats = "0.1.5"
rand = "0.9.1"
reqwest = { version = "0.12.16", features = ["blocking"] }
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
